### ISSUE TITLE
identChar definition looks wrong

### ISSUE THREAD

**Issue by marijnh** [nextjournal/lezer-clojure#7]
```
  identStart { std.asciiLetter | $[<>._=?!*+\-$\u{a1}-\u{10ff}] }
  identChar { identStart (std.digit | ":" | "." | "'" | "#")* }
  simpleIdent { identStart identChar* }
```

Instead of defining valid characters that can continue an ident, `identChar` is defined as starting with an `identStart`, followed by any number of the chars that may occur in a non-start position of an identifier. This seems like it wouldn't match something like `s1` (since it requires the second character to also be an `identStart`).

I assume this is supposed to work something like this instead...

```
  identChar { identStart | std.digit | ":" | "." | "'" | "#" }
```

**Comment by mk** [comment]
Thank you!
